<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class News extends Model
{
    use HasFactory;
    const news = 'news';
    protected $table = 'news';
    public $timestamps = false;

    protected $fillable = [
        'title',
        'content',
        'description',
        'img',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        News::updated(function() {
            Cache::delete(News::news);
        });
    }

    public static function index()
    {
        return Cache::remember(News::news, DAY, function () {
            return News::where('visible', FLAG_ON)->get();
        });
    }

    public function scopeVisible(Builder $query)
    {
        return $query->where('visible', FLAG_ON);
    }
}
